### ISSUE TITLE
Create a release for v1.4.0

### ISSUE THREAD

**Issue by rajbos** [peter-murray/workflow-application-token-action#22]
The marketplace only shows release and not all tags: 

![image](https://user-images.githubusercontent.com/6085745/194898149-b4f9ea61-ef9f-4c18-a3a0-df214c2dd786.png)

I was searching for the version that supports the `github_api_base_url` parameter, which is v1.4.0 and it is not in the releases list, making it harder to find.

**Comment by peter-murray** [comment]
Sorry about that, I have backfilled that release.
