### ISSUE TITLE
Respect `no_proxy` settings next to the proxy settings.

### ISSUE THREAD

**Issue by rajbos** [peter-murray/workflow-application-token-action#23]
With #21 there is now support for proxy settings, which do not adhere to the `no_proxy` settings, breaking in our setup where we set both `http_proxy` and `no_proxy`.

**Comment by rajbos** [comment]
I've been checking to see if I can contribute, and wanted to discuss first about the direction😁.

From what I can see, [https-proxy-agent](https://www.npmjs.com/package/https-proxy-agent) does not support the no_proxy settings 😞. That means we have two options:
1. Add a setting to ignore the `https_proxy` environment variable: `ignore_proxy: false`, which requires user input.
2. Write a check to see if the target url is in the no_proxy list, and if so, do not inject the https-proxy-agent [here](https://github.com/peter-murray/workflow-application-token-action/blob/45d295960b4aae9c44a8e267a61dd61dfd658bf6/lib/github-application.js#L189)

Tagging @peter-murray for visibility.

**Comment by peter-murray** [comment]
Option 1 is the quickest to deliver in this case, but seeing that we are reading the settings from the environment ti does present Option 2 as being a more consistent approach.

If I was to do this, if you explicitly inject the proxy as an `input` to the action, there would be no ignoring the proxy URLs, otherwise why did you inject it?

**Comment by rajbos** [comment]
Good point. Then it's Option 3? 

3. Make the injection of the proxy as `input` **required** and do not load the environment settings at all.

Or would you want do do both 3 and 2 then (sorry if this is getting confusing)?

**Comment by peter-murray** [comment]
After going around the bush a few times with this, I landed on the assumption that the `no_proxy` would be host names, so in the case of GitHub.com would be `api.github.com` in the string and it works in my limited testing.

@rajbos would you mind checking that the branch `no-proxy-support` does what you need it to do before I publish this to `main` and release a new version?

**Comment by rajbos** [comment]
Works like a charm @peter-murray!

I've tested: 
- With our environment settings (HTTPS_PROXY and NO_PROXY), _with_ a `github_api_base_url` set
- With our environment settings (HTTPS_PROXY and NO_PROXY), _without_ a `github_api_base_url` set
- With our environment settings (HTTPS_PROXY and NO_PROXY), _with_ the `https_proxy` variable set

Things work as expected with these combinations! Thanks for turning this around so quickly 🤗.
