### ISSUE TITLE
GitHub is depracating "setOutput" command

### ISSUE THREAD

**Issue by angusjellis** [peter-murray/workflow-application-token-action#25]
GitHub is [deprecating the "setOutput" command](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) in favour of env files.

This means that this action will likely break on May 1st, 2023 if it isn't updated 😿

**Comment by peter-murray** [comment]
Version 2,1 update the actions/core version to resolve this.

**Comment by angusjellis** [comment]
> Version 2,1 update the actions/core version to resolve this.

excellent, thanks for this!
