### ISSUE TITLE
INC - application_private_key

### ISSUE THREAD

**Issue by GregoireF** [peter-murray/workflow-application-token-action#26]
Good evening,

First of all thank you for your tool, I'm a big fan of it!
I am using Terraform for configuration purposes for an organization. When using Terraform to create GitHub Secrets Actions.

Key creation scheme : 
- Follow the tutorial on [README.md]()
- Transforming the PEM key into Base64 for Terraform
- Terraform uses the [Crypto](https://pkg.go.dev/golang.org/x/crypto/nacl/box#pkg-types) tool 
- The key is created on GitHub correctly

When I try to use it through your workflow in this way : 
```sh
- name: Get token
        id: get_token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db
        with:
          application_id: ${{ secrets.ID_AUTOSYNCBOT }}
          application_private_key: ${{ secrets.PEM_AUTOSYNCBOT }}
```

I find myself facing this error when using it: 
```sh
$ Run peter-murray/workflow-application-token-action@8e1ba3bf1619726336[4](https://github.com/wr-projects/first-contributions/actions/runs/3634830314/jobs/6145186475#step:5:5)14f1014e37f17fbadf1db
Error: Error: Input required and not supplied: application_private_key
Error: Failed to initialize GitHub Application connection using provided id and private key
```

Maybe I'm going the wrong way, or maybe the [Crypto](https://pkg.go.dev/golang.org/x/crypto/nacl/box#pkg-types) module provided by Terraform is simply not recognized by your workflow?

Best regards,

**Comment by peter-murray** [comment]
Hi 👋 the `Error: Input required and not supplied: application_private_key` would seem to be implying that the private key itself is not being passed in as that is an early failure; https://github.com/peter-murray/workflow-application-token-action/blob/8e1ba3bf1619726336414f1014e37f17fbadf1db/index.js#L9

**Comment by Develliot** [comment]
I'm seeing something similar where this worked with v1 but not with v2. Still investigating.

I also wanted to say this action is awesome btw

**Comment by Develliot** [comment]
Ah I added 

organization: myorg

and now everything works again.

**Comment by peter-murray** [comment]
Closing as I think this has been answered in the comments here and the error did seem to indicate the value failing a pre check

**Comment by Develliot** [comment]
That must have been a fluke because I have come back after holiday and it looks like it is broken again
