### ISSUE TITLE
application_private_key not found

### ISSUE THREAD

**Issue by Develliot** [peter-murray/workflow-application-token-action#29]
Even though I have application_private_key pointing to a secret in my github action code, it can't be found by this action runs. 

![Screenshot 2023-05-02 at 09 25 09](https://user-images.githubusercontent.com/5347198/235620019-2e6c0897-7a32-4aee-be1e-599c6fbf9e84.png)

I thought I fixed this when I saw my tests run successfully after adding the org attribute, but I have come back from holiday and it isn't working again.

https://github.com/peter-murray/workflow-application-token-action/issues/26

I know the secret exists because when I use peter-murray/workflow-application-token-action@v1 
everything is fine. 

I'm trying to figure out what the difference was between v1 and v2

**Comment by peter-murray** [comment]
Expand your parameters on the failing action step and check to see that there is a masked value for the `application_private_key`. The error being reported there is indicating that the value is not specified or empty and come early in the loading cycle from the `core.getInput()` with a required flag.

Where is is this secret value you are referencing being defined? Could it be an organization secret that is not specifically shared with this repository, or an environment secret that is not being targeted by your run?
