### ISSUE TITLE
Pass GH app token from one job to another

### ISSUE THREAD

**Issue by jnus** [peter-murray/workflow-application-token-action#30]
Trying to generate the GH app token in one job, and using it in another via a output variable, GH will skip assignment due to it being registered as a secret.  Is there any option to not mask the token or another work around to pass the token from one job to another?  Found this, but a lot of boilerplate code -> https://nitratine.net/blog/post/how-to-pass-secrets-between-runners-in-github-actions/

**Comment by peter-murray** [comment]
The jobs boundary in Actions is always going to protect the passing of anything that is masked, i.e. a secret.

The default behaviour today would be try to adopt OIDC or just fetch the necessary token in each of the jobs that need to utilize it. Encrypting things and passing them across the job boundaries is possible, like in the linked example, but this is always going to be subject to your desires and willingness to make such a thing work. There are some companies and use cases where they definitely would not tolerate such a thing.

Is there a particular reason you are looking to pass the token across these boundaries and not fetch the token when you need to in the relevant jobs?

**Comment by jnus** [comment]
@peter-murray  - just optimizing API calls a little bit and keeping things lean, since the workflow will fan out quite a bit. Makes perfectly sense to protect secrets outside the job boundary. I've reverted back to creating a new token for each job instead for now.
